### ISSUE TITLE
打开的是百度

### ISSUE THREAD

**Issue by clippit** [ty-me/caoliu#3]
好大的bug

**Comment by jwz-ecust** [comment]
太坑爹了

**Comment by yohn89** [comment]
最开始是默认打开你们最喜欢的网站，有网友反馈说有`传播淫秽色情信息`的嫌疑，我也认同，所以修改了链接，不过你可以修改一下代码，改成你最爱的网站，见：
https://github.com/yohn89/caoliu/blob/master/caoliu/__init__.py#L6
